### PR TITLE
Python 3 changes

### PR DESCRIPTION
**Pull request by corradio**

### CODE REVIEW

**Comment by corradio** [comment]
For some reason I can't seem to merge your master into this branch..
My two last commits show the changes that need to be made.

**Comment by cclauss** [comment]
Merged into the PR.

**Comment by corradio** [comment]
This was merged into master by the way. We should probabyl have merged it into your branch instead.

**Comment by cclauss** [comment]
There is a merge conflict in parsers/ES_CN.py that is difficult for me to untangle.

**Comment by corradio** [comment]
That's probably related to https://github.com/tmrowco/electricitymap/pull/964.
My recommendation is to use the file from master and then convert if to py3 because most of it was rewritten.

**Pull request merged**
